// Official UCSD Registered Student Organizations (curated subset)
// Source: UCSD Student Organizations database
export const UCSD_CLUBS: string[] = [
  // Academic & Professional
  "Accounting Society",
  "Alpha Kappa Psi (Professional Business)",
  "American Institute of Chemical Engineers (AIChE)",
  "American Medical Student Association (AMSA)",
  "American Society of Civil Engineers (ASCE)",
  "American Society of Mechanical Engineers (ASME)",
  "Association for Computing Machinery (ACM)",
  "Biomedical Engineering Society (BMES)",
  "Chemistry Club",
  "Cognitive Science Student Association",
  "Computer Science & Engineering Society",
  "Data Science Student Society (DS3)",
  "Design Co",
  "Economics Student Association",
  "Engineers Without Borders",
  "Eta Kappa Nu (HKN)",
  "Finance Society",
  "Global Medical Brigades",
  "Graduate Women in Computing",
  "IEEE at UCSD",
  "Institute of Electrical and Electronics Engineers",
  "International Affairs Group",
  "Investment Club",
  "Math Club",
  "Model United Nations",
  "Mortar Board Senior Honor Society",
  "National Society of Black Engineers (NSBE)",
  "Physics Club",
  "Pre-Dental Society",
  "Pre-Law Society",
  "Pre-Medical Association",
  "Pre-Pharmacy Society",
  "Society of Asian Scientists and Engineers (SASE)",
  "Society of Hispanic Professional Engineers (SHPE)",
  "Society of Women Engineers (SWE)",
  "Tau Beta Pi Engineering Honor Society",
  "Theta Tau Professional Engineering Fraternity",
  "Triton Consulting Group",
  "Triton Engineering Student Council (TESC)",
  "Triton Robotics",
  "Triton Software Engineering (TSE)",
  "Women in Computing (WIC)",

  // Cultural & Identity
  "African American Student Union (AASU)",
  "Asian Pacific Islander Student Alliance",
  "Aztlan Cultural",
  "Black Student Union (BSU)",
  "Chinese American Student Association (CASA)",
  "Chinese Student Association (CSA)",
  "Filipino Student Association (FILSA)",
  "Hermanas Unidas",
  "Hong Kong Student Association",
  "Indian Student Association",
  "Japanese Student Association",
  "Korean American Student Association (KASA)",
  "Lambda Theta Nu Sorority",
  "Movimiento Estudiantil Chicano de Aztlán (MEChA)",
  "Muslim Student Association",
  "Pacific Islander Student Association",
  "Pan-Asian Staff Association",
  "Persian Student Organization",
  "Taiwanese American Student Association (TASA)",
  "Thai Student Association",
  "Vietnamese Student Association (VSA)",

  // Community Service
  "Alternative Breaks",
  "Alpha Phi Omega",
  "Circle K International",
  "Flying Samaritans",
  "Global TIES",
  "Habitat for Humanity",
  "Health CASA",
  "International Health Collective",
  "Kaibigang Pilipin@",
  "Kidz Konnect",
  "Rotaract Club",
  "Students for Global Health",
  "Students Rising Above",
  "Volunteer Connection",

  // Sports & Recreation
  "Archery Club",
  "Badminton Club",
  "Baseball Club",
  "Basketball Club",
  "Climbing Club",
  "Cricket Club",
  "Cycling Club",
  "Dance Marathon",
  "Fencing Club",
  "Golf Club",
  "Ice Hockey Club",
  "Judo Club",
  "Lacrosse Club",
  "Martial Arts Club",
  "Rowing Club",
  "Rugby Club",
  "Running Club",
  "Sailing Team",
  "Ski & Snowboard Club",
  "Soccer Club",
  "Surf Club",
  "Swim Club",
  "Table Tennis Club",
  "Tennis Club",
  "Triathlon Club",
  "Ultimate Frisbee",
  "Volleyball Club",
  "Water Polo Club",
  "Yoga Club",

  // Arts & Media
  "A Cappella Groups",
  "ArtPower",
  "Dance Crew Association",
  "Film Production Club",
  "Graphic Design Club",
  "Jazz Club",
  "Photography Club",
  "Saltman Quarterly (Science Magazine)",
  "Stage & Screen Magazine",
  "The Guardian (Student Newspaper)",
  "The Koala",
  "KSDT Radio",
  "Triton Fest",
  "Triton TV",

  // Greek Life
  "Alpha Chi Omega",
  "Alpha Delta Pi",
  "Alpha Epsilon Pi",
  "Alpha Phi",
  "Beta Theta Pi",
  "Chi Omega",
  "Delta Delta Delta",
  "Delta Gamma",
  "Delta Sigma Phi",
  "Kappa Alpha Theta",
  "Kappa Kappa Gamma",
  "Lambda Chi Alpha",
  "Phi Beta Sigma",
  "Phi Delta Theta",
  "Pi Beta Phi",
  "Pi Kappa Alpha",
  "Pi Kappa Phi",
  "Sigma Alpha Epsilon",
  "Sigma Chi",
  "Sigma Nu",
  "Sigma Phi Epsilon",
  "Theta Chi",
  "Zeta Beta Tau",

  // Special Interest
  "Anime & Manga Club",
  "Astronomy Club",
  "Board Game Club",
  "Chess Club",
  "Cooking Club",
  "Cryptocurrency Club",
  "Debate Team",
  "Entrepreneurship Club",
  "Environmental Club",
  "Esports Association",
  "Food Recovery Network",
  "Garden Club",
  "Hiking Club",
  "Investment Banking Club",
  "Music Production Club",
  "Outdoor Adventures",
  "Podcast Club",
  "Real Estate Club",
  "Sustainability Club",
  "TEDxUCSD",
  "Video Game Development Club",
  "Wine Club",
  "Writers' Workshop",
];

export const INTEREST_OPTIONS: string[] = [
  // Outdoors & Adventure
  "Beach trips",
  "Hiking",
  "Surfing",
  "Camping",
  "Skateboarding",
  "Rock climbing",
  "Snowboarding",
  "Yoga",
  "Running",
  "Cycling",

  // Social & Nightlife
  "Concerts & live music",
  "Bar hopping",
  "House parties",
  "Karaoke",
  "Dancing",
  "Food festivals",
  "Wine tasting",
  "Comedy shows",

  // Creative
  "Photography",
  "Painting & art",
  "Film & cinema",
  "Music production",
  "Writing",
  "Graphic design",
  "Fashion",
  "Podcasting",

  // Tech & Academic
  "Coding & hackathons",
  "AI & machine learning",
  "Startups & entrepreneurship",
  "Investing & finance",
  "Research",
  "Robotics",
  "Data science",

  // Lifestyle
  "Cooking & baking",
  "Coffee culture",
  "Thrifting",
  "Travel",
  "Fitness & gym",
  "Meditation",
  "Volunteering",
  "Gaming",
  "Anime & manga",
  "Board games",
  "Reading",
  "Sustainability",

  // Sports
  "Basketball",
  "Soccer",
  "Tennis",
  "Volleyball",
  "Swimming",
  "Baseball",
  "Football",
  "Badminton",
  "Table tennis",
  "Ultimate frisbee",
];
